### ISSUE TITLE
Arduino Due

### ISSUE THREAD

**Issue by AlbiBone** [adafruit/MAX6675-library#16]
The library does not work with Arduino Due (arm processor).

**Comment by FedeEV** [comment]
Hi,

**Comment by FedeEV** [comment]
I give you the link for MAX6675 for arduino DUE: https://mega.nz/file/u813mbzA#znYZpvejzVPvOM0G-tIY4ReS3Wm5W-WQwIgB6PcKJjU    
try it and tell me something if not working,
here is working good

**Comment by AlbiBone** [comment]
Thank you @FedeEV, I will check it. Why don't you share your library on github?

**Comment by ladyada** [comment]
fixed
