### ISSUE TITLE
3 zone 

### ISSUE THREAD

**Issue by mohamad235** [adafruit/MAX6675-library#19]
Hi. My code is true?

**Comment by mohamad235** [comment]
Hi. My code is true?
#include "max6675.h"
//ThermoCouple 3 Zone
//All GND Connected To PIN06
//All VCC Connected To PIN05
//All SCK Connected To PIN04
//All SO Connected To PIN02
//CS01 To Pin03
//CS02 To Pin07
//CS03 To Pin08

int thermo_gnd_pin=6;
int thermo_vcc_pin=5;
int thermo_so_pin=2;
int thermo_sck_pin=4;
int thermo_cs_pin1=3;
int thermo_cs_pin2=7;
int thermo_cs_pin3=8;

MAX6675 thermocouple1(thermo_sck_pin,thermo_cs_pin1,thermo_so_pin);
MAX6675 thermocouple2(thermo_sck_pin,thermo_cs_pin2,thermo_so_pin);
MAX6675 thermocouple3(thermo_sck_pin,thermo_cs_pin3,thermo_so_pin);

void setup() {
Serial.begin(9600);

pinMode(thermo_vcc_pin,OUTPUT);
pinMode(thermo_gnd_pin,OUTPUT);
digitalWrite(thermo_vcc_pin,HIGH);
digitalWrite(thermo_gnd_pin,LOW);

}

void loop() {
 Serial.println(thermocouple1.readCelsius());
  Serial.println(thermocouple2.readCelsius());
   Serial.println(thermocouple3.readCelsius());
 delay(200);
}

**Comment by ladyada** [comment]
contact your vendor for tech support

**Comment by mohamad235** [comment]
My vendor don't tech support
